"use client";

import { useState } from "react";
import { Wand2, Loader2, Check, TriangleAlert } from "lucide-react";
import { SectionCard } from "@/components/ui/SectionCard";
import { EmptyState } from "@/components/ui/EmptyState";
import { answerQuestionnaire } from "@/lib/api/questionnaires";
import { ApiError } from "@/lib/api/client";
import { normalizeQuestionnaires } from "@/lib/api/questionnaire-normalizers";
import { cn } from "@/lib/utils/cn";
import type { QuestionnairesData } from "@/lib/hooks/useQuestionnaires";

type State = "idle" | "running" | "success" | "error" | "unavailable";

export function AnswerAutomation({ data, onAnswered }: { data: QuestionnairesData; onAnswered?: () => void }) {
  const { questionnaires } = data;
  const list = normalizeQuestionnaires(questionnaires.data);
  const [selected, setSelected] = useState("");
  const [state, setState] = useState<State>("idle");
  const [message, setMessage] = useState<string | null>(null);

  async function handleRun() {
    setState("running");
    setMessage(null);
    try {
      await answerQuestionnaire(selected || null);
      setState("success");
      setMessage("Auto-answer requested. Responses will come from the backend.");
      onAnswered?.();
    } catch (err) {
      if (err instanceof ApiError && [404, 405, 501].includes(err.status)) {
        setState("unavailable");
        setMessage("Answer automation is not available on this backend yet.");
      } else {
        setState("error");
        setMessage(err instanceof ApiError ? err.message : "Request failed. Please try again.");
      }
    }
  }

  const selectable = list.filter((q) => q.rawId);

  return (
    <SectionCard title="Answer Automation" subtitle="Request AI-assisted answers" icon={Wand2} accent="purple" className="h-full">
      {questionnaires.isLoading ? (
        <div className="h-24 animate-pulse rounded-xl bg-white/40" />
      ) : selectable.length === 0 ? (
        <EmptyState compact icon={Wand2} title="No questionnaires to answer" description="Upload or sync a questionnaire to request automated answers from the backend." />
      ) : (
        <div className="space-y-3.5">
          <div>
            <label className="mb-1 block text-[12px] font-semibold text-cv-slate">Questionnaire</label>
            <select
              value={selected}
              onChange={(e) => setSelected(e.target.value)}
              className="cv-ring-focus w-full rounded-xl bg-white/65 px-3 py-2 text-[13px] text-cv-ink ring-1 ring-white/70 focus:outline-none"
            >
              <option value="">Select a questionnaire</option>
              {selectable.map((q) => (
                <option key={q.id} value={q.rawId as string}>
                  {q.title}
                </option>
              ))}
            </select>
          </div>
          <p className="text-[11px] leading-relaxed text-cv-slate">
            Answers are generated by the backend automation service — the frontend never fabricates responses.
          </p>
          <button
            type="button"
            onClick={handleRun}
            disabled={state === "running" || !selected}
            className="cv-ring-focus flex w-full items-center justify-center gap-2 rounded-2xl bg-cv-brand py-3 text-sm font-bold text-white shadow-button transition hover:-translate-y-0.5 disabled:opacity-60"
          >
            {state === "running" ? <Loader2 size={16} className="animate-spin" /> : <Wand2 size={16} />}
            {state === "running" ? "Requesting…" : "Request Auto-Answer"}
          </button>
          {state !== "idle" && state !== "running" && message ? (
            <p className={cn("flex items-center gap-1.5 text-[12px] font-medium", state === "success" ? "text-emerald-600" : state === "unavailable" ? "text-amber-600" : "text-rose-600")}>
              {state === "success" ? <Check size={13} /> : <TriangleAlert size={13} />}
              {message}
            </p>
          ) : null}
        </div>
      )}
    </SectionCard>
  );
}
